language: php
git:
  depth: 1
cache:
  directories:
  - "$HOME/.composer/cache"
sudo: false
env:
  global:
  - COMPOSER_ALLOW_XDEBUG=0
matrix:
  include:
  - php: 7.1
    env:
      - CONTAO_VERSION='4.4.*'
  - php: 7.2
    env:
      - CONTAO_VERSION='4.4.*'
  - php: 7.1
    env:
      - CONTAO_VERSION='4.5.*'
  - php: 7.2
    env:
      - CONTAO_VERSION='4.5.*'
  - php: 7.2
    env:
      - CONTAO_VERSION='4.5.*'
      - COVERAGE='--exclude-group contao3 --coverage-clover build/logs/clover.xml'
  fast_finish: true
before_install:
- if [[ ! $COVERAGE ]]; then phpenv config-rm xdebug.ini || true; fi
install:
- if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction
  --quiet; fi
- composer update $COMPOSER_FLAGS --no-interaction --no-suggest
notifications:
  email:
    recipients:
    - digitales@heimrich-hannot.de
    on_success: never
    on_failure: always
  hipchat:
    rooms:
      secure:
before_script:
- travis_wait composer install --no-interaction
script:
- if [[ $COVERAGE ]]; then mkdir -p build/logs; fi
- php vendor/bin/phpunit $COVERAGE
after_script:
- if [[ $COVERAGE ]]; then php vendor/bin/coveralls; fi